/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 ./public/satelite.glb -t
Author: Lexi4 (https://sketchfab.com/mr.alyxey13)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/satelite-0c244a9be4154c848675a0d756bd0bc9
Title: Satelite
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useSnapshot } from "valtio";

import state from "../store";

type GLTFResult = GLTF & {
    nodes: {
        ["��������������������_0"]: THREE.Mesh;
        ["��������������_0"]: THREE.Mesh;
        ["��������������001_0"]: THREE.Mesh;
        ["������009_0"]: THREE.Mesh;
        ["����������_0"]: THREE.Mesh;
        ["����������001_0"]: THREE.Mesh;
        ["��������������003_0"]: THREE.Mesh;
        ["��������������002_0"]: THREE.Mesh;
        ["������������������_0"]: THREE.Mesh;
        ["������������������001_0"]: THREE.Mesh;
        ["��������������004_0"]: THREE.Mesh;
        ["������002_0"]: THREE.Mesh;
        ["��������������005_0"]: THREE.Mesh;
        ["��������������006_0"]: THREE.Mesh;
        ["������_0"]: THREE.Mesh;
        ["������001_0"]: THREE.Mesh;
        ["������003_0"]: THREE.Mesh;
        ["������004_0"]: THREE.Mesh;
        ["������005_0"]: THREE.Mesh;
        ["������006_0"]: THREE.Mesh;
        ["������007_0"]: THREE.Mesh;
        ["������008_0"]: THREE.Mesh;
        ["������010_0"]: THREE.Mesh;
        ["������011_0"]: THREE.Mesh;
        ["������012_0"]: THREE.Mesh;
        ["������013_0"]: THREE.Mesh;
        ["������014_0"]: THREE.Mesh;
        ["������015_0"]: THREE.Mesh;
        ["������016_0"]: THREE.Mesh;
        ["������017_0"]: THREE.Mesh;
        ["������018_0"]: THREE.Mesh;
        ["������019_0"]: THREE.Mesh;
        ["������020_0"]: THREE.Mesh;
        ["������021_0"]: THREE.Mesh;
        ["������������������005_0"]: THREE.Mesh;
    };
    materials: {
        Root: THREE.MeshStandardMaterial;
    };
};

export function Satelite(props: {} & JSX.IntrinsicElements["group"]) {
    const snap = useSnapshot(state);
    const { nodes, materials } = useGLTF("/satelite.glb") as GLTFResult;
    const handleClick = () => {
        state.textArea = !state.textArea;
    };

    return (
        <group {...props} dispose={null}>
            <group
                onClick={handleClick}
                position={[-0.14, -0.06, -0.03]}
                rotation={[-1.86, -0.81, 1.74]}>
                <mesh
                    geometry={nodes["��������������������_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 1.43]}
                    scale={0.99}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["��������������_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 0.49]}
                    scale={[1, 1, 0.21]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["��������������001_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 1.25]}
                    scale={[0.79, 0.79, 0.45]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������009_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, -0.03]}
                    rotation={[-0.12, 0.03, 2.88]}
                    scale={[0.01, 0.01, 0.12]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["����������_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 1.93]}
                    scale={0.47}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["����������001_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 1.93]}
                    scale={0.47}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["��������������003_0"].geometry}
                    material={materials.Root}
                    position={[0.89, -0.27, 0.71]}
                    rotation={[Math.PI / 2, Math.PI / 2, 0]}
                    scale={0.04}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["��������������002_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 1.11]}
                    scale={[0.76, 0.76, 0.43]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������������������_0"].geometry}
                    material={materials.Root}
                    position={[-0.01, 0, 0.35]}
                    rotation={[0, 0, 2.36]}
                    scale={0.7}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������������������001_0"].geometry}
                    material={materials.Root}
                    position={[-0.01, 0, 0.35]}
                    rotation={[0, 0, -2.36]}
                    scale={0.7}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["��������������004_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 0.07]}
                    scale={[0.27, 0.27, 0.29]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������002_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 0.08]}
                    rotation={[0.82, 0.63, -2.64]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["��������������005_0"].geometry}
                    material={materials.Root}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["��������������006_0"].geometry}
                    material={materials.Root}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������_0"].geometry}
                    material={materials.Root}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������001_0"].geometry}
                    material={materials.Root}
                    rotation={[0, 0, Math.PI / 2]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������003_0"].geometry}
                    material={materials.Root}
                    rotation={[0, 0, -Math.PI]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������004_0"].geometry}
                    material={materials.Root}
                    rotation={[0, 0, -Math.PI / 2]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������005_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 0.08]}
                    rotation={[0.82, 0.63, -2.64]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������006_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 0.08]}
                    rotation={[-0.82, 0.63, -0.5]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������007_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 0.08]}
                    rotation={[-0.82, -0.63, 0.5]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������008_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, 0.08]}
                    rotation={[0.82, -0.63, 2.64]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������010_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, -1.04]}
                    rotation={[-2.59, 0.18, 0.28]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������011_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, -1.04]}
                    rotation={[-2.59, -0.17, -0.27]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������012_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, -1.04]}
                    rotation={[2.94, -0.55, -1.95]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������013_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, -1.04]}
                    rotation={[-2.93, -0.54, -1.18]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������014_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, -1.04]}
                    rotation={[2.59, -0.18, -2.86]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������015_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, -1.04]}
                    rotation={[2.59, 0.17, 2.87]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������016_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, -1.04]}
                    rotation={[-2.94, 0.55, 1.19]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������017_0"].geometry}
                    material={materials.Root}
                    position={[0, 0, -1.04]}
                    rotation={[2.93, 0.54, 1.96]}
                    scale={[0.77, 0.04, 0.77]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������018_0"].geometry}
                    material={materials.Root}
                    rotation={[-Math.PI / 2, Math.PI / 4, Math.PI / 2]}
                    scale={[0.38, 0.25, 0.25]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������019_0"].geometry}
                    material={materials.Root}
                    rotation={[-Math.PI / 2, -Math.PI / 4, Math.PI / 2]}
                    scale={[0.38, 0.25, 0.25]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������020_0"].geometry}
                    material={materials.Root}
                    rotation={[Math.PI / 2, -Math.PI / 4, -Math.PI / 2]}
                    scale={[0.38, 0.25, 0.25]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������021_0"].geometry}
                    material={materials.Root}
                    rotation={[Math.PI / 2, Math.PI / 4, -Math.PI / 2]}
                    scale={[0.38, 0.25, 0.25]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
                <mesh
                    geometry={nodes["������������������005_0"].geometry}
                    material={materials.Root}
                    position={[-0.01, 0, 1.42]}
                    scale={[1, 0.06, 1]}>
                    <meshStandardMaterial color={snap.color} />
                </mesh>
            </group>
        </group>
    );
}

useGLTF.preload("/satelite.glb");
